### ISSUE TITLE
Error: both async and sync fetching of the wasm failed

### ISSUE THREAD

**Issue by Danmou** [foxglove/studio#1481]
**Description**
When I try to open a ROS2 bag I get the following error:
Error initializing player
```
Error: both async and sync fetching of the wasm failed
    at Object.f.onAbort (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:541:25152)
    at Ot (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:541:40911)
    at Nn (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:541:41402)
```

- Version: 0.13.1
- OS: Ubuntu 20.04
- ROS2 Galactic

**Steps To Reproduce**
Can't publicly share the data, but here's the output of `ros2 bag info` (it's just 1min of data from a depth camera):
```
Files:             rosbag2_2021_04_22-16_43_13.db3
Bag size:          263.8 MiB
Storage id:        sqlite3
Duration:          59.822s
Start:             Apr 27 2021 20:25:50.909 (1619547950.909)
End:               Apr 27 2021 20:26:50.731 (1619548010.731)
Messages:          1200
Topic information: Topic: /pico_flexx/camera_info | Type: sensor_msgs/msg/CameraInfo | Count: 300 | Serialization Format: cdr
                   Topic: /pico_flexx/image_depth | Type: sensor_msgs/msg/Image | Count: 300 | Serialization Format: cdr
                   Topic: /pico_flexx/image_mono8 | Type: sensor_msgs/msg/Image | Count: 300 | Serialization Format: cdr
                   Topic: /pico_flexx/points | Type: sensor_msgs/msg/PointCloud2 | Count: 300 | Serialization Format: cdr
```

**Comment by amacneil** [comment]
Fixed by https://github.com/foxglove/studio/pull/1509, will be in next release (v0.13.2)
