### ISSUE TITLE
Unable to open ROS 2 bag.

### ISSUE THREAD

**Issue by peredwardsson** [foxglove/studio#1703]
**Description**
Opening a ROS 2 bag I just recorded does not seem to work at all.

- Version: 0.16.0, installed via apt
- OS: Ubuntu 18.04

**Steps To Reproduce**
Open Foxglove and try to open a ros 2 bag by: 
- dragging in the folder (or any individual file). The app shows an error that the file format is not allowed.
- selecting the ROS 2 Bag (Local) option, then select the folder that contains the .db and .yaml files for the recording. Try to use the Select Folder button, but opt to use Open Folder instead since Select Folder appears to be some kind of menu button that opens an empty menu rather than actively selecting a folder. Following error appears:
```
Error: no such column: offered_qos_profiles
    at At.handleError (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:477:33208)
    at At.exec (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:477:31850)
    at t.open (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:5:96788)
    at async u.open (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:9:5449)
    at async t (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:9:1474)
    at async er.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:4189:6822)
    at async Cy.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:4182:25091)
```

**Expected Behavior**
The bag opens and the topics become available in the studio.

**Additional information**
It looks like the button isn't doing what it should be (see
![image](https://user-images.githubusercontent.com/15907557/130951808-f73a376c-c6a4-407e-9238-f91d15ca9662.png)
). Happy to provide additional information on request.

**Comment by jtbandes** [comment]
Fixing in https://github.com/foxglove/rosbag2-web/pull/4 & https://github.com/foxglove/rosbag2-node/pull/3.
