### ISSUE TITLE
Make `yarn serve` work in nodejs v17

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2011]
```
➜  studio ✗ yarn serve
1% setup initialize[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (/Users/jhurliman/Documents/Code/foxglove/studio/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /Users/jhurliman/Documents/Code/foxglove/studio/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at Object.interpolateName (/Users/jhurliman/Documents/Code/foxglove/studio/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at getWorkerFilename (/Users/jhurliman/Documents/Code/foxglove/studio/node_modules/monaco-editor-webpack-plugin/out/index.js:41:24)
    at /Users/jhurliman/Documents/Code/foxglove/studio/node_modules/monaco-editor-webpack-plugin/out/index.js:127:77
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/jhurliman/Documents/Code/foxglove/studio/node_modules/monaco-editor-webpack-plugin/out/index.js:127:43) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by jhurliman** [comment]
This appears to be working now
