### ISSUE TITLE
Error initializing player when message definition contains an empty string constant

### ISSUE THREAD

**Issue by luisrayas3** [foxglove/studio#2039]
**Description**

Chokes on bagfile with empty string constant.

```
Error: invalid syntax at line 1 col 26:

  string RECOVERY_MODE_NONE=
                           ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

A character matching /[a-zA-Z0-9_]/ based on:
    constantField$ebnf$1 → constantField$ebnf$1 ● /[a-zA-Z0-9_]/
    constantField →  ● constantField$ebnf$1
    main → _ stringType __ ● constantField _ stringConstantValue _ main$ebnf$8
A space token based on:
    _$subexpression$1 →  ● %space
    _ →  ● _$subexpression$1
    main → _ stringType arrayType __ field ● _ main$ebnf$3 simple
A assignment token based on:
    assignment →  ● %assignment
    stringConstantValue →  ● assignment
    main → _ stringType __ constantField _ ● stringConstantValue _ main$ebnf$8
A comment token based on:
    comment →  ● %comment
    main$ebnf$3 →  ● comment
    main → _ stringType arrayType __ field _ ● main$ebnf$3 simple

    at u.feed (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:176:656)
    at file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:183:504
    at Array.forEach (<anonymous>)
    at b (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:183:397)
    at g (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:183:163)
    at _e.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/8517.js:1:11727)
    at async w.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/8517.js:1:1084)
    at async ye.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/8517.js:2:2747)
    at async w.initialize (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/8517.js:1:1084)
```

- Version: 0.20.1
- OS: Ubuntu 18.04

**Steps To Reproduce**

 Load a bagfile which includes a message type that defines an empty string constant (this is accepted by rosmsg)

**Expected Behavior**

bagfile content loads

**Actual Behavior**

small red icon shows up, when clicking it shows "Error initializing player" and clicking into that shows the error message above.

**Comment by luisrayas3** [comment]
BTW this is using ROS1, not ROS2

**Comment by jtbandes** [comment]
Thanks for the report!

**Comment by jtbandes** [comment]
We will upgrade rosmsg soon, pending https://github.com/foxglove/rosmsg/pull/18
