### ISSUE TITLE
Error: Expected IndexData (4) but found 7 at BagReader.readRecordFromBuffer

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2363]
https://drive.google.com/file/d/1BRYQUVsX9GIWxt9tIag7MSK9DDcFl6HF/view?usp=sharing

This bag loads fine in 0.24.0 but fails to load in `main` (tested with https://github.com/foxglove/studio/commit/2da50ff45ff6fcd326ecfe59c1faa46a1c3e6453).

```
An error was encountered during bag parsing. This usually happens if the bag is somehow malformed.
Error: Expected IndexData (4) but found 7
  at BagReader.readRecordFromBuffer (webpack-internal:///../../node_modules/@foxglove/rosbag/dist/esm/BagReader.js:171:19)
  at BagReader.readRecordsFromBuffer (webpack-internal:///../../node_modules/@foxglove/rosbag/dist/esm/BagReader.js:150:33)
  at BagReader.readChunk (webpack-internal:///../../node_modules/@foxglove/rosbag/dist/esm/BagReader.js:140:30)
  at async BagReader.readChunkMessages (webpack-internal:///../../node_modules/@foxglove/rosbag/dist/esm/BagReader.js:86:24)
  at async Bag.readMessages (webpack-internal:///../../node_modules/@foxglove/rosbag/dist/esm/Bag.js:84:30)
  at async BagDataProvider.getMessages (webpack-internal:///../../packages/studio-base/src/randomAccessDataProviders/BagDataProvider.ts:277:13)
  at async ApiCheckerDataProvider.getMessages (webpack-internal:///../../packages/studio-base/src/randomAccessDataProviders/ApiCheckerDataProvider.ts:139:32)
  at async eval (webpack-internal:///../../packages/studio-base/src/randomAccessDataProviders/RpcDataProviderRemote.ts:32:30)
```

**Comment by defunctzombie** [comment]
@jhurliman re-assigning to you - I can confirm this doesn't open but also don't know how this bag was made. Maybe the bag _is_ malformed?
