### ISSUE TITLE
ROS node error when I add turtle1/pose to RAW message panel

### ISSUE THREAD

**Issue by LeZhang13** [foxglove/studio#3496]
**Description**

- Version:1.12.1
- OS:Ubantu 18.04 (Virtual Machine）
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):ROS 1 native
- ROS distro (if applicable): turtlesim

**Steps To Reproduce**

Step by step with the Blog "Running Your First ROS Node on Ubuntu, macOS, or Windows"
Connect Foxglove to  ROS node turtlesim
Add [Topic Graph] panel to see Topic and node , this step is OK.
![image](https://user-images.githubusercontent.com/89899260/172127181-81038d31-e7e6-426d-9c24-598ba23d4c6d.png)
Add [Raw Messages] panel and add /turtle1/pose to see the structure of the topic's messages: NOK
![image](https://user-images.githubusercontent.com/89899260/172127434-96f354a1-aa88-4f76-ab5a-678cb813d702.png)

**Expected Behavior**
To see the turtle1/pose in RAW message

**Actual Behavior**
ROS Node Error happened.
Error: Subscribing to /turtle1/pose at http://tedzhang-virtual-machine:44671/ failed (Error: requestTopic("/turtle1/pose") from http://tedzhang-virtual-machine:44671/ failed. err=Error: XML-RPC call "requestTopic" to http://tedzhang-virtual-machine:44671/ returned 502: "Bad Gateway"), this connection will be dropped
    at RosNode._subscribeToPublisher (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:26617:32)
    at async file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:26577:69

**Comment by foxymiles** [comment]
What did you set as your ROS_HOSTNAME when you connected to the ROS1 source?

<img width="804" alt="ros1-dialog" src="https://user-images.githubusercontent.com/93935560/172161329-9d5d59fe-957b-4b88-9964-74625893da24.png">

**Comment by LeZhang13** [comment]
Hi, Same as yours
![image](https://user-images.githubusercontent.com/89899260/172284481-070983ba-0d45-4eb2-abda-21f1ef6f1b09.png)

**Comment by LeZhang13** [comment]
By the way , I also try to use ROS  native connect to play rosbag.
1. roscore
2. Foxglove connect ROS 1(same as last picture)
3. rosbag play xxx.bag
4. Foxglove show error
![image](https://user-images.githubusercontent.com/89899260/172303843-1ee2d45c-7deb-4b7f-8b2c-3f5e3d1bf471.png)
Also show bad gateway

**Comment by LeZhang13** [comment]
> What did you set as your ROS_HOSTNAME when you connected to the ROS1 source?
> 
> <img alt="ros1-dialog" width="804" src="https://user-images.githubusercontent.com/93935560/172161329-9d5d59fe-957b-4b88-9964-74625893da24.png">
HI, foxymiles, I found all ros native connect will show error : bad gateway .
I make a publisher to show my web camera video, and connect foxglove,  also show same error.
![image](https://user-images.githubusercontent.com/89899260/172553937-4f883c3d-0c74-4aa8-ae10-e3b8a1be1ab5.png)
and
![image](https://user-images.githubusercontent.com/89899260/172554083-b0f70c14-eb79-4098-b985-ec935171a6f1.png)
and 
![image](https://user-images.githubusercontent.com/89899260/172554151-d42286d3-3bff-4724-a908-73eccf40f1c6.png)

**Comment by defunctzombie** [comment]
These are ROS1 network setup (and env/hostname) resolution errors. Your nodes are reporting their hostname as `tedzhang-virtual-machine` however your desktop (where you run studio) is either not able to resolve that hostname or the port is being blocked.

Using ROS1 across hosts (even with virtual machines) requires that the ROS_HOSTNAME that all nodes are broadcasting to the master for themselves be resolvable from all other nodes that want to subscribe. It also requires full and open TCP network connectivity between all these nodes (and Studio which is just another node).

I recommend reading http://wiki.ros.org/ROS/NetworkSetup and making sure all your nodes have a correct ROS_HOSTNAME set that is resolvable across all nodes and studio (consider using an IP address rather than hostname to be sure).

Closing this because the issue is with network and environment setup and is expected behavior when trying to use ROS1 across hosts.

**Comment by LeZhang13** [comment]
> These are ROS1 network setup (and env/hostname) resolution errors. Your nodes are reporting their hostname as `tedzhang-virtual-machine` however your desktop (where you run studio) is either not able to resolve that hostname or the port is being blocked.
> 
> Using ROS1 across hosts (even with virtual machines) requires that the ROS_HOSTNAME that all nodes are broadcasting to the master for themselves be resolvable from all other nodes that want to subscribe. It also requires full and open TCP network connectivity between all these nodes (and Studio which is just another node).
> 
> I recommend reading http://wiki.ros.org/ROS/NetworkSetup and making sure all your nodes have a correct ROS_HOSTNAME set that is resolvable across all nodes and studio (consider using an IP address rather than hostname to be sure).
> 
> Closing this because the issue is with network and environment setup and is expected behavior when trying to use ROS1 across hosts.

Thanks for your reply, but my foxglove studio and ROS all in my Ubantu vertical machine environment, I will check my Ubantu firewall.
