### ISSUE TITLE
Docker Build giving panic:runtime error

### ISSUE THREAD

**Issue by REGATTE** [foxglove/studio#4468]
**Description**

I've cloned the repo, and built it locally, by `docker build -t local .`, and the build process was fine. Once I start to run in by `docker run --rm -p "8080:8080" local`, it gives me `panic: runtime error: invalid memory address or nil pointer dereference`

- Version: 1.25.0
- OS: MacOS Docker
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): None
- ROS distro (if applicable):None 

**`DID NOT CHANGE ANY CODE`**

**Steps To Reproduce**

```
cd studio
docker build -t local .
docker run --rm -p "8080:8080" local
```

**Expected Behavior**

Start Foxglove studio on `localhost:8080`

**Actual Behavior**

```
regattes-MacBook-Pro:studio regatte$ docker run --rm -p "8080:8080" local
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xae7688]

goroutine 1 [running]:
github.com/caddyserver/caddy/v2/cmd.Flags.String({0x1841740?}, {0x1a7645e?, 0x1a7c02a?})
	github.com/caddyserver/caddy/v2@v2.6.0/cmd/main.go:267 +0x48
github.com/caddyserver/caddy/v2/cmd.Flags.Bool({0x0?}, {0x1a7645e?, 0x417b53?})
	github.com/caddyserver/caddy/v2@v2.6.0/cmd/main.go:275 +0x25
github.com/caddyserver/caddy/v2/modules/caddyhttp/fileserver.cmdFileServer({0x0?})
	github.com/caddyserver/caddy/v2@v2.6.0/modules/caddyhttp/fileserver/command.go:74 +0x125
github.com/caddyserver/caddy/v2/cmd.caddyCmdToCoral.func1(0xc0003d0000?, {0x1a734ec?, 0x2?, 0x2?})
	github.com/caddyserver/caddy/v2@v2.6.0/cmd/cobra.go:114 +0x2c
github.com/spf13/cobra.(*Command).execute(0xc0003d0000, {0xc00008abc0, 0x2, 0x2})
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2a77a60)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.6.0/cmd/main.go:64 +0x5c
main.main()
	./main.go:39 +0x17

```

** Things I tried **

1. Changed caddy version to caddy:2.6.0-alpine -> same error
2. updated docker and go, (maybe, just maybe it would help, maybe) -> same error

**

**Comment by REGATTE** [comment]
Thank you!
