### ISSUE TITLE
ros2 MarkerArray failed to parse, invalid typed array length

### ISSUE THREAD

**Issue by mrkbac** [foxglove/studio#4698]
**Description**

- Version: 1.29.0
- OS: ubuntu 22.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): ros2 native
- ROS distro (if applicable): humble

**Steps To Reproduce**

When running the following python code foxglove reports "Error receiving messages on "/markers"

```
Error: Failed to parse 2328 byte message on "rt/markers": Invalid typed array length: 1072693247
    at Participant.<anonymous> (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:6:115248)
    at EventEmitter.emit (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:1202:12257)
    at Participant.handleUserData (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:211:24763)
    at Participant.handleData (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:211:19783)
    at Participant.handleDataMsg (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:211:18309)
    at Participant.handleUdpMessage (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:211:14684)
    at EventEmitter.emit (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:1202:12314)
    at file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:4749:32078
    at UdpSocketRenderer.messagePort.onmessage (file:///opt/Foxglove%20Studio/resources/app.asar/renderer/main.js:4749:32418)
```

```python3
import sys

import rclpy
from rclpy.node import Node
from visualization_msgs.msg import Marker, MarkerArray

class Visu_Node(Node):
    def __init__(self):
        super().__init__('visu_node')
        self.idx = 0

        self.markers = MarkerArray()
        self.markers.markers.clear()

        for x in range(10):
            m = Marker()
            m.header.stamp = self.get_clock().now().to_msg()
            m.header.frame_id = "/map"
            m.id = self.idx
            m.action = Marker.ADD
            m.type = Marker.CYLINDER

            m.scale.x = 1.0
            m.scale.y = 1.0
            m.scale.z = 1.0

            m.pose.position.x = x * 1.0

            self.markers.markers.append(m)

        self.pub = self.create_publisher(MarkerArray, "/markers", 10)
        self.create_timer(0.1, self.timer)

        self.timer()

    def timer(self):
        self.pub.publish(self.markers)


def main(args=None):
    rclpy.init(args=args)

    minimal_publisher = Visu_Node()
    rclpy.spin_once(minimal_publisher)
    rclpy.spin(minimal_publisher)
    minimal_publisher.destroy_node()

    rclpy.shutdown()


if __name__ == '__main__':
    main(sys.argv)


```

**Comment by jtbandes** [comment]
As a workaround, can you try a Rosbridge connection?

**Comment by jtbandes** [comment]
Going forward, we plan to deprecate and remove the ROS 2 native connection (https://github.com/foxglove/studio/issues/4900). We are working on a new [foxglove_bridge](https://github.com/foxglove/ros-foxglove-bridge), which will provide improved performance and reliability over the Rosbridge and native connections. You can already use the new bridge today (see the README). Stay tuned for upcoming announcements about the new bridge!
