### ISSUE TITLE
build docker container from the root of the repo leads to exception

### ISSUE THREAD

**Issue by cherkavi** [foxglove/studio#6272]
**Description**
Build container locally leads to the exception instead of proper build

- Version: latest
- Platform: Linux.Debian

**Steps To Reproduce**
```sh
docker build .
```

**Error**
```
 ---> Running in d990cad347d9
Syntax Error: Unexpected identifier
(function (exports, require, module, __filename, __dirname) { version https://git-lfs.github.com/spec/v1
                                                                      ^^^^^

SyntaxError: Unexpected identifier
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/corepack/dist/corepack.js:41360:22)
    at Module2._compile (/usr/local/lib/node_modules/corepack/dist/corepack.js:41328:41)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require2 (/usr/local/lib/node_modules/corepack/dist/corepack.js:41313:24)
    at c4 (/root/.cache/node/corepack/yarn/3.3.1/yarn.js:390:10475)
    at Tf (/root/.cache/node/corepack/yarn/3.3.1/yarn.js:390:11318)
The command '/bin/sh -c yarn install --immutable' returned a non-zero code: 1
```

**Comment by cherkavi** [comment]
https://github.com/foxglove/studio/issues/5158
